version: '3'

services:

    mongo:
        container_name: mongodb
        image: mongo:latest
        environment:
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=root
            - MONGO_INITDB_DATABASE=project
        ports: 
            - 27018:27017
        volumes: 
            - ./database

    mongo-express:
        container_name: mongodbms
        image: mongo-express
        environment:
            - ME_CONFIG_MONGODB_SERVER=mongo
            - ME_CONFIG_MONGODB_PORT=27017
            - ME_CONFIG_MONGODB_ENABLE_ADMIN=false
            - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
            - ME_CONFIG_MONGODB_AUTH_USERNAME=root
            - ME_CONFIG_MONGODB_AUTH_PASSWORD=root
            - ME_CONFIG_BASICAUTH_USERNAME=DASistemas
            - ME_CONFIG_BASICAUTH_PASSWORD=Ordinario!
        depends_on:
            - mongo
        ports:
          - "8888:8081"

    scraper:
        container_name: scraper
        build: 
            context: ./Puertos/Scraper
            dockerfile: dockerfile
        depends_on: mongo

    frontend:
        container_name: frontend
        build:
            context: ./Puertos/Frontend
            dockerfile: dockerfile